SELECT ri.FOOD_TYPE, ri.REST_ID, ri.REST_NAME, fm.FAVORITES FROM REST_INFO ri
JOIN
(
    SELECT 
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
)fm
ON ri.FOOD_TYPE = fm.FOOD_TYPE AND ri.FAVORITES = fm.FAVORITES
ORDER BY ri.FOOD_TYPE DESC;
