SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    ui.GENDER,
    COUNT(DISTINCT os.USER_ID) AS USERS
FROM ONLINE_SALE os 
INNER JOIN 
(
    SELECT
        USER_ID,
        GENDER
    FROM USER_INFO 
    WHERE GENDER IS NOT NULL
)ui
ON os.USER_ID = ui.USER_ID
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER ASC
;