# SELECT * FROM (
#     SELECT 
#         ai.*, ao.DATETIME AS OUT_TIME
#     FROM ANIMAL_INS ai
#     LEFT OUTER JOIN ANIMAL_OUTS ao
#     ON ai.ANIMAL_ID = ao.ANIMAL_ID
#     WHERE ao.DATETIME IS NULL
#     ORDER BY ai.DATETIME DESC
#     LIMIT 3
# ) r
# ORDER BY r.DATETIME ASC
# ;

SELECT 
    ai.NAME, ai.DATETIME
FROM ANIMAL_INS ai
LEFT OUTER JOIN ANIMAL_OUTS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE ao.DATETIME IS NULL
ORDER BY DATETIME ASC
LIMIT 3
;

