SELECT r.FLAVOR FROM
(
    SELECT fh.FLAVOR, fh.TOTAL_ORDER + j.TOTAL_ORDER AS fh_j FROM FIRST_HALF fh
    INNER JOIN
    (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY
        GROUP BY FLAVOR
    )j
    ON fh.FLAVOR = j.FLAVOR
    ORDER BY fh_j DESC
    LIMIT 3
)r
