SELECT 
    hd.DEPT_ID,
    hd.DEPT_NAME_EN,
    av.AVG_SAL 
FROM HR_DEPARTMENT hd
INNER JOIN
(
    SELECT 
        DEPT_ID,
        ROUND((SUM(SAL)/COUNT(*)), 0) AS AVG_SAL 
    FROM HR_EMPLOYEES 
    GROUP BY DEPT_ID
)av
ON hd.DEPT_ID = av.DEPT_ID
ORDER BY AVG_SAL DESC;