
SELECT b.CATEGORY, SUM(bts.TOTAL_SALES) AS TOTAL_SALES FROM BOOK b
INNER JOIN
(
    SELECT 
        bs.BOOK_ID,
        SUM(bs.SALES) AS TOTAL_SALES
    FROM BOOK_SALES bs 
    WHERE bs.SALES_DATE LIKE '2022-01%'
    GROUP BY bs.BOOK_ID
) bts
ON b.BOOK_ID = bts.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC
;