SELECT
    fp.CATEGORY,
    fp.PRICE AS MAX_PRICE,
    fp.PRODUCT_NAME 
FROM FOOD_PRODUCT fp
INNER JOIN
(
    SELECT
        CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE 
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) fp2
ON fp.CATEGORY = fp2.CATEGORY AND fp.PRICE = fp2.MAX_PRICE
WHERE fp.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
;